services:
  cd_backend:
    image: cd_backend:1.0.0
    container_name: ${BACKEND_HOST}
    build: ./cd_backend
    env_file: .env
    environment:
      NODE_OPTIONS: --disable-warning=ExperimentalWarning
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./cd_backend:/cd_backend
      - db_data:/cd_backend/data

  cd_cms:
    image: cd_cms:1.0.0
    container_name: ${CMS_HOST}
    build:
      context: ./cd_cms
      dockerfile: Dockerfile
    env_file: .env
    environment:
      VITE_BACKEND_URL: http://${BACKEND_HOST}:${BACKEND_PORT}
      VITE_SUPABASE_URL: ${SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    ports:
      - ${CMS_PORT}:${CMS_PORT}
    volumes:
      - ./cd_cms:/cd_cms
      - /cd_cms/node_modules
    depends_on:
      - cd_backend

volumes:
  db_data:
