version: '3.8'

services:
  cd_backend:
    image: ${BACKEND_IMAGE:-cd_backend}:${TAG:-latest}
    build:
      context: ./cd_backend
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - '8083:8083'
    environment:
      - NODE_ENV=production
      - USE_NEON_DB=true
      - NEON_DB_HOST=${NEON_DB_HOST}
      - NEON_DB_PORT=${NEON_DB_PORT}
      - NEON_DB_USERNAME=${NEON_DB_USERNAME}
      - NEON_DB_PASSWORD=${NEON_DB_PASSWORD}
      - NEON_DB_DATABASE=${NEON_DB_DATABASE}
      - NEON_DB_SSL=true
    volumes:
      - ./data/uploads:/app/data/uploads
    networks:
      - app_network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  cd_cms:
    image: ${CMS_IMAGE:-cd_cms}:${TAG:-latest}
    build:
      context: ./cd_cms
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - '5173:80'
    environment:
      - NODE_ENV=production
    depends_on:
      - cd_backend
    networks:
      - app_network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  app_network:
    driver: bridge
# No need for volume for database storage since we're using Neon DB
