version: '3.9'
services:
  app:
    image: app:1.0.0
    container_name: ${SERVER_HOST}
    build: .
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    #   - ./server:/server
    #   - server-v-node-modules:/server/node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: ${DB_HOST}
    restart: always
    # build:
    #   context: ./database
    #   dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - database-v:/var/lib/postgresql/data
    command: '-p ${DB_PORT}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -p ${DB_PORT} -U ${DB_USER} -d ${DB_DATABASE}']
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  #   server-v-node-modules:
  #     name: 'server-v-node-modules'
  database-v:
    name: 'database-v'
