services:
  cd_backend:
    build:
      context: ./cd_backend
      dockerfile: Dockerfile
      target: development
    env_file: .env
    environment:
      NODE_ENV: development
      NODE_OPTIONS: --disable-warning=ExperimentalWarning
    ports:
      - 127.0.0.1:${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./cd_backend:/cd_backend
      - ./cd_backend/node_modules:/cd_backend/node_modules
      - db_data:/cd_backend/data
    command: npm run start
    networks:
      - app_network

  cd_cms:
    build:
      context: ./cd_cms
      dockerfile: Dockerfile
      target: development
    env_file: .env
    environment:
      NODE_ENV: development
      VITE_BACKEND_URL: http://localhost:${BACKEND_PORT}
      VITE_SUPABASE_URL: ${SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    ports:
      - 127.0.0.1:${CMS_PORT}:${CMS_PORT}
    volumes:
      - ./cd_cms:/cd_cms
      - ./cd_cms/node_modules:/cd_cms/node_modules
    command: npm run dev
    depends_on:
      - cd_backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
