services:
  cd_backend:
    build:
      context: ./cd_backend
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - 127.0.0.1:${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - db_data:/cd_backend/data
    env_file: .env
    environment:
      - NODE_ENV=production
    networks:
      - app_network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  cd_cms:
    build:
      context: ./cd_cms
      dockerfile: Dockerfile
      target: production
      args:
        VITE_BACKEND_URL: ${BACKEND_URL}
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - 127.0.0.1:${CMS_PORT}:80
    depends_on:
      - cd_backend
    restart: unless-stopped
    networks:
      - app_network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    external: true
    name: cd_admin-db_data
