version: '3.9'
services:
  cd_backend:
    image: cd_backend:1.0.0
    container_name: ${SERVER_HOST}
    build: .
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/cd_backend

    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
