name: Database Backup

on:
  schedule:
    - cron: "0 1 * * *" # Runs at 1 AM every night
  workflow_dispatch: # Allows manual triggering
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  backup:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >> ~/.ssh/config << EOF
          Host deployment_target
            HostName ${{ secrets.VM_HOST }}
            User ${{ secrets.VM_USER }}
            Port ${{ secrets.VM_SSH_PORT }}
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOF

      - name: Create Database Backup
        run: |
          ssh deployment_target '
            mkdir -p /opt/cd_admin/backups
            BACKUP_DIR="/opt/cd_admin/backups"
            docker run --rm \
              -v db_data:/data \
              -v $BACKUP_DIR:/backup \
              ubuntu tar czf /backup/database_backup_$(date +%Y%m%d_%H%M%S).tar.gz /data
          '

      - name: Cleanup Old Backups
        run: |
          ssh deployment_target '
            BACKUP_DIR="/opt/cd_admin/backups"
            # Remove backups older than 30 days
            find $BACKUP_DIR -type f -name "*.tar.gz" -mtime +30 -delete
          '

      - name: Prepare Backup Directory
        run: mkdir -p ./backups

      - name: Copy Backup to Runner
        run: |
          scp deployment_target:/opt/cd_admin/backups/*.tar.gz ./backups/

      - name: Upload Backup to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: database-backup-${{ github.sha }}
          path: ./backups/*.tar.gz
          retention-days: 30
