name: Delete Duplicate Captions

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  delete-duplicate-captions:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Duplicate Captions Deletion
        run: |
          curl -X POST \
            -H "x-api-key: ${{ secrets.ADMIN_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"dryRun": false}' \
            https://${{ secrets.API_URL }}/delete-duplicate-captions
