name: Sync Fragments

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync
        run: |
          curl -X POST \
            -H "x-api-key: ${{ secrets.ADMIN_API_KEY }}" \
            https://${{ secrets.API_URL }}/sync-fragments
